<!--
% Common elements of a DCF document
-->

<!-- UNCOMMENT THE NEXT LINE FOR PRODUCTION -->
<!--
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lora">
-->

```{r include=FALSE}
require(mosaic)
require(knitr)
require(dplyr)
require(tidyr)
require(NHANES)
require(mosaicData)

# For typesetting
library(xtable)
library(ggthemes)
baseTheme <- theme_tufte( ticks=TRUE )
library(xkcd)
funTheme <- theme_xkcd()
library(ScoreR)
opts_chunk$set( tidy=FALSE, out.width="50%", comment=NA,
                warning=FALSE,message=FALSE)
options( width=60, 
         na.rm=TRUE,
         # Printing tables
         xtable.type="html",
         xtable.include.rownames=FALSE)
require(DCF)
```

<!-- Change this to add parameters for the scroller -->

```{r include=FALSE}
scroller_hook = function(before, options, envir) {
    width=options$scroller
    if ( ! width %in% c(300,600)) {
      warning( "scroller must be either 300 or 600")
      width=300
      }
    if (before) {
      return(sprintf('<div class="table-scroller%d">',width))
    } else {
      return('</div>')
    }
}
knit_hooks$set( scroller=scroller_hook ) 
```

