---
title: "Data and Computing Fundamentals"
author: "Home Page"
date: "Fall 2014"
output:
  html_document:
    css: ~/KaplanFiles/DCF-2014/ReOrganizedJune10/CSS/DCF-style.css
    fig_caption: yes
    toc: yes
---

## To do

* In DCFdevel, redefine `summarize()` and `summarise()` so that the basic functions have `na.rm=TRUE`????
* Change world cities population from integer to numeric.
* Change NaN in NHANES to NA
* Change all data in DCF to follow Capital dataframe name, lower-case variable name.
* BabyNamesYearly should be changed to just baby names.


## Week 1: Infrastructure

**Class Meeting**: Tuesday 10 Sept.

**Notes**: 
* [The Structure of Data](CourseNotes/DataOrganization/DraftNarrative.html) ** NEED TO  break out exercises.**
* [A Quick Start with R](CourseNotes/Rbasics/R-Basics.html)
* [Paths and file types](CourseNotes/DataOrganization/FileTypes.html)


**Other resources**:  
* Videos: [Starting RStudio], [Creating an Rmd Document], [R Chunks in Rmd], [Handing in an Rmd Document]

[Assignment One](Assignments/Assignment-One.html) due Wednesday 18 Sept.

## Week 2

**Class Meeting**: Tuesday 17 Sept.

**Notes**:
* [R Commands](CourseNotes/Rbasics/DraftNarrative.html) NEEDS TO BE WRITTEN
* [Data Verbs](CourseNotes/BasicDataCommands/DraftNarrative.html) NEED TO Pull out exercises and the early notes about NHANES to turn into exercises.
* [Glyphs, Frames, and Guides](CourseNotes/GraphicsConstructDeconstruct/DraftNarrative.html) IN PROGRESS ...

[Assignment Two](Assignment-Two.html) due Thursday 19 Sept.


EXERCISE COLLECTIONS: [graphics](CourseNotes/GraphicsConstructDeconstruct/Exercises.html)

## Week Three

**Class Meeting**: Tuesday 17 Sept.

**Notes**:
* [More Data Verbs](CourseNotes/BasicDataCommands/MoreDataVerbs.html)
* Tidying Data
* Classic charts
* More Graphics Properties: Facets, layers.

[Assignment Three](Assignment-Three.html) due Thursday 26 Sept.


## Week 4: Data Backstory

## Week 5: Stats

## Week 6: Multiple Variables

## Week 7: Cleaning, Scraping



## DTK To Do List



The time log. [Link to enter new data](https://docs.google.com/forms/d/1lH02nfMVvVmCxyus3TBHQvG58pV-cGDEcTfaBJAIk3k/viewform)

<iframe src="https://docs.google.com/spreadsheets/d/1ROnT3PBL_iVguJQPKrGAXncf-wHKzEYHQQtE7c6JYG4/pubhtml?widget=true&amp;headers=false"></iframe>

