---
title: "DCF Topics"
author: "Daniel Kaplan"
date: "April 23, 2014"
output: html_document
---

```{r include=FALSE}
require(dplyr)
```

See also : `DCF-2014/Narrative/Overall_Outline.Rmd`  Consolidate that file into this one.

Also `Narrative/Ideas.Rmd`.

Also `Sections/Introduction/Overview.Rmd`

## Background

[PCAST Big Data report](http://www.whitehouse.gov/sites/default/files/microsites/ostp/PCAST/pcast_big_data_and_privacy_-_may_2014.pdf) about privacy, mainly.  [Another PCAST report](http://www.whitehouse.gov/sites/default/files/docs/big_data_privacy_report_5.1.14_final_print.pdf) about opportunities with big data.

A radio show about [data science, "still sexy?"](http://www.information-management.com/pdfs/DMRadio-04-03-14_DataScience.mp3)

## Data Organization

1) Cases and variables

Call it a **datatable**: one word to give it a technical meaning, restricted to a rigid format.

Rows and columns

Quantitative and categorical

There are other forms of data, e.g. photographs, movies, text.  The datatable is arguably the most important.  Many other forms of data eventually get reduced to datatables for the purposes of display and analysis.

Emphasis the **case**.

* How the meaning of an individual case can change.  A datatable gives a **view of data**.  There are typically other views possible, sometimes derived from a particular view.

Runners as individuals and as groups, e.g. by sex, by age group, by sex and age group.

Flight data involving two airports compared to airport data (e.g. latitude and longitude) on its own.  Taxi time versus airport.  Airplane model data: mass and engines

### Wide and narrow: 

What's a case and what's a variable is somewhat fluid.

* Individual runners in multiple years: wide and narrow
* 96-well plate and spectrophotometer
* UN data where the case is a country and where the case is a country in a year and where the case is a particular measurement in a country in a year

It's not that one form is right and the others are wrong.  Some forms are better for a particular purpose, e.g. making a scatterplot of year-2 versus year-1 is easily handled with wide data.

**Shaping** data means transcribing data from one datatable form to another. (It doesn't mean distorting data or altering or redacting).

Many of the techniques for working with data are about shaping it, so that you can present it in the way that you think best rather than in the ways that happen to match the original shapes.

**Database** is a collection of datatables.  Often, the datatables have different cases.

### Reading and Storing Data

Various common formats: CSV, XLSX

Informal formats (e.g. the Cherry Blossom race) for human consumption. 

Different ways data are distributed: interactive, static files, via URL 

Data Scraping

## Basics of Markdown

Start them out with the knitr side-by-side display function, so that things are re-run as they get changed.

## Templates

## Basics of R

* prompt, expression, value
* values and arithmetic and grouping parentheses
* functions, arguments and parentheses
    * help
    * tab in RStudio
* assignment with `<-`
* named arguments with `=`, ... name`=`value`.  Note, the name comes
* character strings.  You're welcome to use quotes around the name of an argument.
    * names of files, labels, levels of categorical variables
* data frames
* numeric, factor, character data
    * We often think of factors as if they were characters.
    * Technical stuff: factors vs character, class()
* booleans and comparison
    * `==` not `=` to test for equality.  Testing for equality is different than giving a named argument.
* packages and names like `mosaic::Galton`
    * names are case sensitive
    * how you can see that a package is not installed
    * how you can see that a package is not loaded
    * how to install a package
    * CRAN and gitHub packages
* copying and replacing
    * functions return a value that is distinct from the original
    * Use assignment `<-` with a new name to make a copy.
    * Use `<-` with an existing name to replace the existing object
    

Bailing out:

* ESC

Commands, dialogs, chunks, environments
* In the console, you can't scroll up to edit, as you might do with a word processor.
* In an Rmd file, you can scroll up and edit, but remember that you have to re-run the commands.
* When compiling a Rmd file, it's always done in a new environment.  That differs from running the chunks


## Graphics

### Presentation Tables

It may seem odd to start a section on graphics with text, but concise text, easily assimulated by eye, is a form of graphics.



#### Example: Word Counts

Look at different genres --- show the leading non-common words.

#### Word Cloud

Counts don't always do it.

[Graphics Zoo](GraphicsZoo/GraphicsZoo.html)


Why is a picture worth a thousand words? 

What are the basic features we want to display? Comparison, extent, individual cases in context, relationships, connections, ...

### One Case at a Time: **Individuals**

1) Scatterplot
#) Dotplot
#) Box-and-whiskers plot
#) Barplot
    a) stacked
#) Parallel Axes


### Two Cases at a Time: **Connections**

1) Graph
    [A blog tutorial on igraph](http://www.r-bloggers.com/network-visualization-in-r-with-the-igraph-package/) shows how to set colors, etc.  [A more detailed tutorial](http://www.lsi.upc.edu/~CSN/lab/session1.pdf)
    a) Directed
    #) Undirected
#) Tree

### Many Cases at a Time: **Collectives**

1) density
#) histogram
#) hexbin


### Order of display of a variable

Why choosing a good ordering for categorical variables is important.

* A complicated case: <../Examples/JobGrowth/jobGrowth.Rmd>


Hadley's [layered grammar of graphics](http://mimno.infosci.cornell.edu/info3300/readings/layered-grammar.pdf)

An essay about [presenting data with graphics](http://schoolofdata.org/handbook/courses/data-to-diagrams/)

[Applied Data Science from Columbia](http://columbia-applied-data-science.github.io/appdatasci.pdf)

[Manyeyes graphics examples](http://www.manyeyes.com/software/analytics/manyeyes/)

### Time Series

You could think about these as a single case with an elaborate glyph.

Need some case studies with time series.  Economics?  Growth?  The runners times over the years
in Cherry Blossom?

## Data Table Operations

1) Select variables  (Relational PROJECT)
#) Filter  (RELATIONAL SELECT)
    a) head, tail --- to pull out the early ones
#) Mutate
    a) conditional choice
#) Group  (RELATIONAL GROUP)
    a) tally
        * Minneapolis Mayor's race.  Do a simple tally and ask "Who won?"  Actually the law requires ... and move on to `removeOne()`.
        * Refactor Galton to have information for each family: father, mother, nkids.  Then, for the height data: sex, height, family.  In your example, say that Galton has already been joined with family.
#) Arrange (RELATIONAL SORT)
#) Join (RELATIONAL JOIN)
    a) inner
    b) left
    c) semi
    d) anti
    
    
## Dimension Reduction

1) Clustering
#) Principal components

## Modeling

1) Linear
#) Smoother
#) Classification Tree



## Cleaning Data

Define a function for each of the really important things.  Make this into a `cleaningFunctions` package.

* substitution: getting rid of the commas in the zip-code population data.  See
<file:///Users/kaplan/KaplanFiles/DCF/DCF-2013/Data/ZipCodes/getZipPopulation.html>

* Checking numbers, mis-spellings: DCF 2013 `Notes/Day4/CleaningTheBirds.html`

* Break text into individual words.

[School of Data](http://schoolofdata.org/handbook/courses/data-cleaning/)

## Scraping Data, data sources

[Quandl](http://www.quandl.com/)

Genetics?

[Web technologies task view](http://cran.r-project.org/web/views/WebTechnologies.html)

