
## Some genetics in R

<http://martinsbioblogg.wordpress.com/2014/07/04/finding-the-distance-from-chip-signals-to-genes/>

## SNPS in R

<https://github.com/rOpenSci/rsnps> ask Paul O about this.


[Paper on Rmd in undergraduate work](http://escholarship.org/uc/item/90b2f5xh) summarized in [phys.org](http://phys.org/news/2014-02-scientific-young.html)

Many (mostly useless) [open data from government sites](http://www.data.gov/open-gov/)

Baby names from 1880 to 2012 from Social Security Administration [link](http://www.ssa.gov/oact/babynames/names.zip), [baby names in New York](http://catalog.data.gov/dataset/baby-names-beginning-2007)  See also this graphic.  

A large collection of interactive graphs: http://rcharts.io/gallery/

http://www.stat.cmu.edu/~cshalizi/statcomp/13/

A large list of miscellaneous data: http://www.inside-r.org/howto/finding-data-internet

[Oracle client from R session](http://www.inside-r.org/node/48947)

Web Scraping [the basics](http://quantifyingmemory.blogspot.co.uk/2014/02/web-scraping-basics.html), [two](http://quantifyingmemory.blogspot.co.uk/2014/02/web-scraping-part2-digging-deeper.html), [three](http://quantifyingmemory.blogspot.com/2014/03/web-scraping-scaling-up-digital-data.html),  [part four](http://quantifyingmemory.blogspot.com/2014/03/web-scraping-working-with-apis.html)

### Facebook

Shiny app that displays [FaceBook Network](http://tuxette.nathalievilla.org/?tag=igraph&lang=en) this seems to include scraping software.

Data mining on facebook friends <http://tuxette.nathalievilla.org/?p=953&lang=en>

[Description of an R bootcamp for scientists](http://gettinggeneticsdone.blogspot.com/2014/03/software-carpentry-at-uva-redux.html)


[Huge baseball database](http://www.seanlahman.com/baseball-archive/statistics/) which can be read into R using the `Lahman` package.

* Reading Google Drive docs into R [blog description](http://www.r-bloggers.com/download-all-documents-from-google-drive-with-r/?utm_source=feedburner&utm_medium=email&utm_campaign=Feed%3A+RBloggers+%28R+bloggers%29)

### XKCD Graphics

<http://stackoverflow.com/questions/12675147/how-can-we-make-xkcd-style-graphs-in-r>

### Maps

rmaps package for R.  See [this blog](https://mail.google.com/mail/u/0/#inbox/144f0f70078a7ed4) original [here](http://mockquant.blogspot.com/2014/03/seamless-analytical-environment-by-wdi.html).

### Strings

A book about R string processing: <http://blog.revolutionanalytics.com/2014/03/strings-in-r-free-ebook.html>

### OK Cupid dataset 

https://github.com/evee746/okcupid

50,000 or so records.

### More about NHANES

http://www.r-bloggers.com/analyze-the-national-health-and-nutrition-examination-survey-nhanes-with-r/

### Sankey diagrams

Network diagrams showing flows and subsets.  See [this blog](http://lamages.blogspot.com/2014/03/sankey-diagrams-with-googlevis.html).  Suitable for alumni-job type data.

### E-book on Data Science

This [book](http://blog.revolutionanalytics.com/2014/03/free-ebook-on-big-data-and-data-science.html) is free.

### Materials from Graphics Editor at NYT

http://simplystatistics.org/2012/06/01/interview-with-amanda-cox-graphics-editor-at-the-new/

And some other pointers to Amanda Cox’s work and thoughts:

https://source.opennews.org/en-US/articles/nyts-amanda-cox-wins-internet/

https://twitter.com/search?q=amanda%20cox&src=typd

### Large list of data-science resources

http://datascienc.es/resources/

### Lots of visualizations

http://www.manyeyes.com/software/analytics/manyeyes/

### Video about Data Journalism

http://datajournalism.stanford.edu/

#### and another

http://learning.blogs.nytimes.com/2010/08/23/teaching-with-infographics-places-to-start/

### Data Graphics Blogs

<http://inspiredm.com/20-essential-infographics-data-visualization-blogs/>

### Taxonomy Package

<http://www.r-bloggers.com/taxize-v0-3-0-update-a-new-data-source-taxonomy-in-writing-and-ubio-examples/>

Dendrogram extensions <http://www.r-statistics.com/2014/07/the-dendextend-package-for-visualizing-and-comparing-trees-of-hierarchical-clusterings-slides-from-user2014/>

### Network Diagrams 

[In ggplot2](http://is-r.tumblr.com/post/38459242505/beautiful-network-diagrams-with-ggplot2)

[and this one](http://sumtxt.wordpress.com/2011/07/02/visualizing-networks-with-ggplot2-in-r/)

* Color <http://wilkinsondarren.wordpress.com/2013/05/24/colour-guide-for-scientific-graphs-and-illustrations/> move this to DCF

* World Bank data <http://cran.r-project.org/web/views/WebTechnologies.html>

## GGPLOT Resources

* Heat maps: <http://www.showmeshiny.com/heatmaps/>

* Interactive ggplot <http://www.showmeshiny.com/ggplot-live/>



## Shiny and data

* Weather in different cities: <http://www.showmeshiny.com/weather-compare/>

## Background: reports, media

[PCAST Big Data report](http://www.whitehouse.gov/sites/default/files/microsites/ostp/PCAST/pcast_big_data_and_privacy_-_may_2014.pdf) about privacy, mainly.  [Another PCAST report](http://www.whitehouse.gov/sites/default/files/docs/big_data_privacy_report_5.1.14_final_print.pdf) about opportunities with big data.

A radio show about [data science, "still sexy?"](http://www.information-management.com/pdfs/DMRadio-04-03-14_DataScience.mp3)

## Landsat data

See [this blog](http://dankelley.github.io/r/2014/07/01/landsat.html)

